/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApplyMessageCard: typeof import('./sidePanel/components/card/ApplyMessageCard.vue')['default']
    ChatHeader: typeof import('./sidePanel/views/ChatHeader.vue')['default']
    ChatHistory: typeof import('./sidePanel/views/ChatHistory.vue')['default']
    ChatInput: typeof import('./sidePanel/views/ChatInput.vue')['default']
    ChatList: typeof import('./sidePanel/views/ChatList.vue')['default']
    CloseIcon: typeof import('./sidePanel/components/icon/CloseIcon.vue')['default']
    ContentApp: typeof import('./content/ContentApp.vue')['default']
    DownIcon: typeof import('./sidePanel/components/icon/DownIcon.vue')['default']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HistoryBtn: typeof import('./sidePanel/components/button/HistoryBtn.vue')['default']
    HistoryIcon: typeof import('./sidePanel/components/icon/HistoryIcon.vue')['default']
    Input: typeof import('./sidePanel/components/input/Input.vue')['default']
    OptionApp: typeof import('./options/OptionApp.vue')['default']
    OptionBtn: typeof import('./sidePanel/components/button/OptionBtn.vue')['default']
    SendIcon: typeof import('./sidePanel/components/icon/SendIcon.vue')['default']
    SendMessageBtn: typeof import('./sidePanel/components/button/SendMessageBtn.vue')['default']
    SettingsBtn: typeof import('./sidePanel/components/button/SettingsBtn.vue')['default']
    SettingsIcon: typeof import('./sidePanel/components/icon/SettingsIcon.vue')['default']
    SidePanelApp: typeof import('./sidePanel/SidePanelApp.vue')['default']
    UserMessageCard: typeof import('./sidePanel/components/card/UserMessageCard.vue')['default']
  }
}
